# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: ZIP Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: zip build.zip ./* -r
    - name: Upload Build Folder
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: build.zip
    - name: Create a Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
        